### ISSUE TITLE
Line 303 on yippi/object.py breaks Artist search

### ISSUE THREAD

**Issue by JoseMHC** [rorre/yippi#4]
Apparently, the update on the file to make __repr__ "more pretty" ended up breaking the code;
`def __repr__(self):
    return "Artist - " + str(name)`
The error that follows says that the variable 'name' is not defined.
Same happens in various instances of __repr__ below that one.

**Comment by rorre** [comment]
Should be fixed on https://github.com/rorre/yippi/commit/4dc87a7af94166912c530e3942b8d75741d4022e commit
