### ISSUE TITLE
Licencing, LGPLv3 or GPLv3?

### ISSUE THREAD

**Issue by Deer-Spangle** [rorre/Yippi#65]
The readme here says the project is licenced under LGPLv3, but the licence file seems to be GPLv3.

I guess it is meant to be LGPLv3?
It would be helpful if that licence file was corrected, as otherwise it forces all projects which use this library to also be GPLv3

**Comment by rorre** [comment]
Ah, it should be LGPLv3, no idea what happened.

Will fix when tomorrow--thanks for the heads up.

**Comment by Deer-Spangle** [comment]
Thank you!

**Comment by Deer-Spangle** [comment]
Ooh, could you update the pypi lib too?

**Comment by rorre** [comment]
Will do soon, theres a few things especially on docs that I still need to
work on.
