### ISSUE TITLE
Multi-user usage

### ISSUE THREAD

**Issue by Deer-Spangle** [rorre/Yippi#76]
I'm looking at a system where I want to have multiple users able to use the client, but what's the best way to handle that?
If I create a client instance for each user, then it won't be obeying the rate limit.

I could call `Yippi.login()` before each call to `Yippi.posts()` but then that's open to race conditions, unless I wrap it with locks. But maybe that's the best option.

Any thoughts or advice?

**Comment by Deer-Spangle** [comment]
Ah, darn, I was thinking I could just have a wrapper and lock, like so:

```
class E6ClientWrapper:

    def __init__(self, base_username: str, base_api_key: str) -> None:
        self.client = YippiClient("Hallo", "??", "dr-spangle")
        self.lock = RLock()
        self.username = base_username
        self.api_key = base_api_key
        self.client.login(self.username, self.api_key)
        
    def posts(self, query: str, login: Optional['E6Key']) -> List[Post]:
        with self.lock:
            if login:
                self.client.login(login.username, login.api_key)
            posts = self.client.posts(query)
            self.client.login(self.username, self.api_key)
        return posts
```

But of course, the posts are each given a reference to the Yippi client, which will later change login, and any attempt to update them would be done with the wrong account.

**Comment by rorre** [comment]
> If I create a client instance for each user, then it won't be obeying the rate limit.
This isn't the case, unless you mean multiple instances in different process then yes, but if you have multiple instances in the same process, it shouldn't exceed the limit. The limiter is placed in a global variable in `AbstractYippi`, and all of the clients uses that as its limiter. So no matter how much instances you make, it will still use the same limiter.

**Comment by Deer-Spangle** [comment]
Oh! I suppose so yeah, I guess I missed that! That does make things easier then, thank you!
